sqlcipher.patch was updated against sqlcipehr
./providers/sqlcipher/sqlcipher.patch was regenerated against upstream
source of sqlcipher. It was necessary, since the following error was
observed:

sqlite3.c: In function ‘sqlcipher_openssl_hmac’:
sqlite3.c:17150:12: error: storage size of ‘hctx’ isn’t known
   HMAC_CTX hctx;

The methodology to generate sqlcipher.patch was taken from the following
file: ./providers/sqlcipehr/NOTE_for_new_SQLCipher_version.

This problem was also mentioned as the bug: 781832