Make trml2html.py and trml2pdf.py executable
They need to be installed in their respective package directories.
Currently:

$ python /usr/bin/trml2html.py
Traceback (most recent call last):
  File "/usr/bin/trml2html.py", line 27, in <module>
    from . import utils
ImportError: attempted relative import with no known parent package

Historically they were installed in subdirectories of /usr/bin, but that
changed with:
06da33a4b ("Reports: Do not install sub-directories in /usr/bin Bug #
594115", 2011-06-16)

Also make sure their executable bits are set, as that is tested for in
gda_report_rml_document_run_as_html() and
gda_report_rml_document_run_as_pdf().